apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-redis1
  namespace: testing
spec:
  clusterServiceClassExternalName: azure-rediscache
  clusterServicePlanExternalName: basic
  parameters:
    resourceGroup: SOUTHCENTRAL
    cacheName: acs-k8-redis
    parameters:
      location: southcentralus
      enableNonSslPort: true
      sku:
        name: Basic
        family: C
        capacity: 0
